export const AUTHENTICATE = "AUTHENTICATE";
export const DEAUTHENTICATE = "DEAUTHENTICATE";
export const FETCH_EDITOR = "FETCH_EDITOR";
export const SAVE_EDITOR = "SAVE_EDITOR";
export const FETCH_SIDEBAR = "FETCH_SIDEBAR";
export const CREATE_SIDEBAR = "CREATE_SIDEBAR";
export const SET_ACTIVEID = "SET_ACTIVEID";
export const FETCH_ACTIVEID = "FETCH_ACTIVEID";
export const UPDATE_EDITOR = "UPDATE_EDITOR";
export const SIGNIN_AUTH = "SIGNIN_AUTH";
export const SIGNUP_AUTH = "SIGNUP_AUTH";
export const SIGNOUT_AUTHSIGNOUT_AUTH = "SIGNOUT_AUTH";
export const DESTROY_SESSION = "DESTROY_SESSION";
export const UPDATE_SIDEBAR = "UPDATE_SIDEBAR";
export const SET_AUTHID = "SET_AUTHID";



