export const AUTHENTICATE = "AUTHENTICATE";
export const DEAUTHENTICATE = "DEAUTHENTICATE";
export const FETCH_EDITOR = "FETCH_EDITOR";
export const SAVE_EDITOR = "SAVE_EDITOR";
export const FETCH_SIDEBAR = "FETCH_SIDEBAR";
export const SAVE_SIDEBAR = "SAVE_SIDEBAR";

